
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://dl.bintray.com/apache/couchdb/mac/1.6.1/Apache-CouchDB-1.6.1.zip && unzip Apache-CouchDB-1.6.1.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then open "Apache CouchDB.app"/ && sleep 5 ; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2017-03-19-a/swift-DEVELOPMENT-SNAPSHOT-2017-03-19-a-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-DEVELOPMENT-SNAPSHOT-2017-03-19-a-ubuntu14.04.tar.gz   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=swift-DEVELOPMENT-SNAPSHOT-2017-03-19-a-ubuntu14.04/usr/bin:$PATH    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install couchdb clang-3.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo couchdb -b && sleep 5 ; fi

script:
  - swift build
  - swift test 
